### ISSUE TITLE
#include <crypt.h> compilation terminated

### ISSUE THREAD

**Issue by TomTomTommi** [princeton-vl/infinigen#225]
# Describe the bug
I following the README file to install infinigen, but meet an error. I don't have sudo permissions and conda support.
I first create a new environment using mamba and use 
```
mamba install conda-forge::gxx=11.4.0 mesalib glew glm menpo::glfw3
export C_INCLUDE_PATH=$CONDA_PREFIX/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$CONDA_PREFIX/include:$CPLUS_INCLUDE_PATH
export LIBRARY_PATH=$CONDA_PREFIX/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH
```
to install the dependencies, then  `pip install -e .` but face the error.
[logs.txt](https://github.com/princeton-vl/infinigen/files/15092259/logs.txt)

### Platform
- HPC Clusters

I also tried another cluster which support conda, but the error still exists. The log is also attached as below.
[logss.txt](https://github.com/princeton-vl/infinigen/files/15093092/logss.txt)

**Comment by araistrick** [comment]
The error in the first log seems to be finding "crypt.h" which I have never seen before. Please check you can find "crypt.h" in your include paths somewhere, or google around for issues of this form e.g. https://github.com/stanford-futuredata/ColBERT/issues/309 

In the second the error is cant find glm.hpp which I have seen before a lot, but should be resolved by the conda commands you ran. please check you can find glm.hpp in your conda include paths.

**Comment by TomTomTommi** [comment]
It is in `~/anaconda3/envs/infinigen/include/glm/glm.hpp`
I tried `sudo apt-get install libglm-dev` and also conda, but still have this error.
after `make terrain`, it has:
```
rm -rf infinigen/terrain/*.egg-info
rm -rf infinigen/terrain/__pycache__
rm -rf infinigen/terrain/build
bash scripts/install/compile_terrain.sh
compiled lib/cuda/utils/FastNoiseLite.so
compiled lib/cuda/elements/voronoi_rocks.so
compiled lib/cuda/elements/upsidedown_mountains.so
compiled lib/cuda/elements/ground.so
compiled lib/cuda/elements/warped_rocks.so
compiled lib/cuda/elements/mountains.so
compiled lib/cuda/elements/landtiles.so
compiled lib/cuda/elements/atmosphere.so
compiled lib/cuda/elements/waterbody.so
compiled lib/cuda/surfaces/chunkyrock.so
compiled lib/cuda/surfaces/cobble_stone.so
compiled lib/cuda/surfaces/cracked_ground.so
compiled lib/cuda/surfaces/dirt.so
compiled lib/cuda/surfaces/ice.so
compiled lib/cuda/surfaces/mountain.so
compiled lib/cuda/surfaces/mud.so
compiled lib/cuda/surfaces/sand.so
compiled lib/cuda/surfaces/sandstone.so
compiled lib/cuda/surfaces/snow.so
compiled lib/cuda/surfaces/soil.so
compiled lib/cuda/surfaces/stone.so
compiled lib/cpu/utils/FastNoiseLite.so
compiled lib/cpu/elements/voronoi_rocks.so
compiled lib/cpu/elements/upsidedown_mountains.so
compiled lib/cpu/elements/ground.so
compiled lib/cpu/elements/warped_rocks.so
compiled lib/cpu/elements/mountains.so
compiled lib/cpu/elements/landtiles.so
compiled lib/cpu/elements/atmosphere.so
compiled lib/cpu/elements/waterbody.so
compiled lib/cpu/surfaces/chunkyrock.so
compiled lib/cpu/surfaces/cobble_stone.so
compiled lib/cpu/surfaces/cracked_ground.so
compiled lib/cpu/surfaces/dirt.so
compiled lib/cpu/surfaces/ice.so
compiled lib/cpu/surfaces/mountain.so
compiled lib/cpu/surfaces/mud.so
compiled lib/cpu/surfaces/sand.so
compiled lib/cpu/surfaces/sandstone.so
compiled lib/cpu/surfaces/snow.so
compiled lib/cpu/surfaces/soil.so
compiled lib/cpu/surfaces/stone.so
compiled lib/cpu/meshing/cube_spherical_mesher.so
compiled lib/cpu/meshing/frontview_spherical_mesher.so
compiled lib/cpu/meshing/uniform_mesher.so
compiled lib/cpu/meshing/utils.so
In file included from source/cpu/soil_machine/SoilMachine.cpp:18:
source/cpu/soil_machine/layermap.h:37:10: fatal error: glm/glm.hpp: No such file or directory
   37 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:11: terrain] Error 1
```

**Comment by TomTomTommi** [comment]
it's the dependencies, now fixed
