### ISSUE TITLE
I ran the getting started code for indoor room code on a mac and got an error -Crashed: 09/18 11:54PM outputs/my_dataset/67b253bb/logs/coarse.err reason="ValueError:  No configurable matching 'BlueprintSolidifier'." node=None fatal=True

### ISSUE THREAD

**Issue by andytriboletti** [princeton-vl/infinigen#327]
# Describe the bug
I am on Mac OS Sequoia. I ran the starter code and got an error.

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

### What command did you run?
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --pipeline_overrides LocalScheduleHandler.use_gpu=False --overwrite

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.

Crashed: 09/18 11:54PM outputs/my_dataset/67b253bb/logs/coarse.err reason="ValueError:  No configurable matching 'BlueprintSolidifier'." node=None fatal=True

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -v -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: 
- GPU (?) :
- GPU Driver Version (?) :
- RAM (GB):

# Additional context

**Comment by andytriboletti** [comment]
I copied the singleroom.gin from config_indoors to config_nature cause I couldnt figure out how to point it to the indoor folder

**Comment by araistrick** [comment]
Apologies for the error, the issue here is that myself/someone added a _two_ `--pipeline_overrides` fields, and argparse is only taking the second one (containing LocalScheduleHandler) but NOT the first one, which specifies to run `generate_indoors` instead of `generate_nature`

This issue appears to have already been fixed in the most up to date docs, please try pulling the latest version. The correspinding version of that example command should be:
```
screen python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True 
```

Let me know if this does not resolve the issue

**Comment by andytriboletti** [comment]
It's still an issue

I ran
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --overwrite --pipeline_overrides LocalScheduleHandler.use_gpu=False

I got outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
Crashed: 09/27 10:42PM outputs/my_dataset/61725392/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True


Full log:


(infinigen) andy@andys-pc:~/infinigen$ python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --overwrite --pipeline_overrides LocalScheduleHandler.use_gpu=False
Failed to open dir (No such file or directory): /run/user/1002/gvfs/
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/andy/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:CUSTOMGT_PATH=PosixPath('/home/andy/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
Using get_slurm_banned_nodes()=[]
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 1
------------------------------------------------------------
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 09/27 10:42PM -> 09/27 10:42PM
Crashed: 09/27 10:42PM outputs/my_dataset/61725392/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.09
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------
(infinigen) andy@andys-pc:~/infinigen$


Running on ubuntu wsl
